lookback_hours = 24

[zenn]
feeds = [
    "https://zenn.dev/topics/ai/feed",
    "https://zenn.dev/topics/chatgpt/feed",
    "https://zenn.dev/topics/flutter/feed",
    "https://zenn.dev/topics/go/feed",
    "https://zenn.dev/topics/langchain/feed",
    "https://zenn.dev/topics/langgraph/feed",
    "https://zenn.dev/topics/llm/feed",
    "https://zenn.dev/topics/mcp/feed",
    "https://zenn.dev/topics/nodejs/feed",
    "https://zenn.dev/topics/rust/feed",
    "https://zenn.dev/topics/svelte/feed",
    "https://zenn.dev/topics/typescript/feed",
    "https://zenn.dev/topics/javascript/feed",
    "https://zenn.dev/topics/raspberrypi/feed",
    "https://zenn.dev/topics/githubactions/feed",
    "https://zenn.dev/topics/tailwindcss/feed",
    "https://zenn.dev/topics/機械学習/feed",
    "https://zenn.dev/topics/dify/feed",
    "https://zenn.dev/topics/nin/feed",
    "https://zenn.dev/topics/claude/feed",
]

[qiita]
feeds = [
    "https://qiita.com/tags/python/feed",
    "https://qiita.com/tags/tauri/feed",
]

[llm]
openai_model = "gpt-4.1-nano"
prompt = """
"""

[discord]
webhook_url = "https://discord.com/api/webhooks/123456789012345678/abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
